#service: default

runtime: nodejs
vm: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
health_check:
  enable_health_check: False
resources:
  cpu: 0.1
  memory_gb: 0.5
  disk_size_gb: 10